# pylint: disable=C0116, C0115
from typing import Optional, Protocol


class BackendProtocol(Protocol):
    def __init__(self, resource_location=None, endline="", **kwargs): ...
    def write(self, message: str, timeout: Optional[int] = None): ...

    def query(self, message: str, timeout: Optional[int] = None) -> str: ...

    def read(self, timeout=None) -> str: ...

    def write_and_read(self, message: str, timeout: Optional[int] = None) -> str: ...

    def close(self): ...
